### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.Services.Common

### ISSUE THREAD

**Issue by timabell** [jcdickinson/tfsslackbot#7]
Got this error on service startup:

	System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Services.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
	File name: 'Microsoft.VisualStudio.Services.Common, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
	   at Microsoft.TeamFoundation.Client.TfsConnection.LoadFromCache(Uri serverUrl, ICredentials credentials, ICredentialsProvider credentialsProvider)
	   at Microsoft.TeamFoundation.Client.TfsConnection..ctor(Uri uri, String locationServiceRelativePath)
	   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection..ctor(Uri uri, Boolean fromFactory)
	   at Microsoft.TeamFoundation.Client.TfsTeamProjectCollection..ctor(Uri uri)
	   at SlackBot.Tfs.TfsChatMessageSink.<InitializeAsync>d__8.MoveNext() in C:\repo\tfsslackbot\SlackBot.Tfs\TfsChatMessageSink.cs:line 58
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
	   at SlackBot.Configuration.SinkConfigurationElementCollection.<CreateSinks>d__1.MoveNext() in C:\repo\tfsslackbot\SlackBotService\Configuration\SinkConfigurationElementCollection.cs:line 44
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
	   at SlackBot.SlackBotService.<OnStart>d__6.MoveNext() in C:\repo\tfsslackbot\SlackBotService\SlackBotService.cs:line 63

	WRN: Assembly binding logging is turned OFF.
	To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
	Note: There is some performance penalty associated with assembly bind failure logging.
	To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Win 10, VS 2015.

**Comment by timabell** [comment]
http://stackoverflow.com/questions/29757680/how-to-checkout-files-from-tfs-using-c-sharp-without-being-dependent-on-visual-s

**Comment by jcdickinson** [comment]
I'm a bit flooded at the moment, but I appreciate this feedback and will look into it.

**Comment by timabell** [comment]
Thanks. I think it's just to do with different versions of VS installing these dlls in different places. I had the same problem with git-tfs I think. Doesn't sound like there's a good solution. Maybe one day ms will release them as a nuget package like they should have in the first place! I'll let you know when I get this working, I'm also short on time.

**Comment by timabell** [comment]
This is similar and is worth looking into https://github.com/git-tfs/git-tfs/issues/832

**Comment by timabell** [comment]
fixed in my branch be using the nuget packages. I'll do a PR when I have a working system

**Comment by timabell** [comment]
okay not quite fixed. see #10

**Comment by timabell** [comment]
Got some more info https://twitter.com/tfsbuck/status/688900899402584064

> Please use the official NuGet packages rather than nuget-bot.

https://blogs.msdn.microsoft.com/buckh/2015/08/10/nuget-packages-for-tfs-and-visual-studio-online-net-client-object-model/

**Comment by timabell** [comment]
got it working on my branch, needs some tidying up before I can do a PR. Also not sure if it'll support older / on-premise TFS
https://github.com/timabell/tfsslackbot/tree/wip

**Comment by jcdickinson** [comment]
Just want to confirm that one of your PRs fixed this?

**Comment by timabell** [comment]
yep, cheers
